pull_request_rules:
  - name: Label PRs from renovate to automerge
    conditions:
      - author=renovate[bot]
    actions:
      label:
        add:
          - automerge
  - name: Close PRs when build check fails
    conditions:
      - check-failure=Build Debug APK
      - label = automerge
    actions:
      close:
        message: This pull request has been automatically closed by Mergify due to
          failed build check.
  - name: Automatic merge
    description: Merge when PR passes all branch protection and has label automerge
    conditions:
      - label = automerge
    actions:
      merge:
